name: fresh_harvest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  http: ^1.1.0
  shared_preferences: ^2.0.15
  firebase_core: ^2.16.0
  firebase_database: ^10.5.7
  image_picker: ^1.1.2
  crypto: ^3.0.3
  firebase_auth: ^4.20.0
  bcrypt: ^1.1.3
  intl: ^0.19.0
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.jpg
    - assets/images/vegetable.png
    - assets/images/fruit.png
    - assets/user_avatar.png
    - assets/QR.jpg
