// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3VpXGLRnZpxYfdBO5UNSnPV2eMhCgcYM',
    appId: '1:1093377170976:web:6b32db27de1d0291f3e645',
    messagingSenderId: '1093377170976',
    projectId: 'freshharvest-96950',
    authDomain: 'freshharvest-96950.firebaseapp.com',
    storageBucket: 'freshharvest-96950.appspot.com',
    measurementId: 'G-WDJ5SEJEB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVRYjFkx9L8cEy1x9k8TQ5rXGIoyRbKFs',
    appId: '1:1093377170976:android:a2df088d07281c84f3e645',
    messagingSenderId: '1093377170976',
    projectId: 'freshharvest-96950',
    storageBucket: 'freshharvest-96950.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIpWIwXZV0R6SnUegYfRtaQotdzNLvBk',
    appId: '1:1093377170976:ios:46dc4607917f4db1f3e645',
    messagingSenderId: '1093377170976',
    projectId: 'freshharvest-96950',
    storageBucket: 'freshharvest-96950.appspot.com',
    iosBundleId: 'com.example.freshHarvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIpWIwXZV0R6SnUegYfRtaQotdzNLvBk',
    appId: '1:1093377170976:ios:46dc4607917f4db1f3e645',
    messagingSenderId: '1093377170976',
    projectId: 'freshharvest-96950',
    storageBucket: 'freshharvest-96950.appspot.com',
    iosBundleId: 'com.example.freshHarvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3VpXGLRnZpxYfdBO5UNSnPV2eMhCgcYM',
    appId: '1:1093377170976:web:940f565d931c4afcf3e645',
    messagingSenderId: '1093377170976',
    projectId: 'freshharvest-96950',
    authDomain: 'freshharvest-96950.firebaseapp.com',
    storageBucket: 'freshharvest-96950.appspot.com',
    measurementId: 'G-DFTVEQSHEV',
  );
}
